name: test 

services:
  frontend:
    container_name: production_frontend
    build:
      context: ./front
    networks:
      - production_network

  backend: 
    container_name: production_backend
    build:
      context: ./backend
    networks:
      - production_network
      
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - production_network
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend

networks:
  production_network: