name: legenda 

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - webdata:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - webdata:/usr/share/nginx/html

volumes:
  letsencrypt:
  webdata: