name: test 

services:
  frontend:
    container_name: production_frontend
    build:
      context: ./front
    networks:
      - production_network

  backend: 
    container_name: production_backend
    build:
      context: ./backend
    networks:
      - production_network
      
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme-challenge:/tmp/acme-challenge
    ports:
      - 80:80
      - 443:443
    networks:
      - production_network
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend

  letsencrypt:
    container_name: "certbot"
    image: certbot/certbot
    command: sh -c "certbot certonly --webroot -w /tmp/acme-challenge/ -d features.roolegenda.ru --text --agree-tos --email general-fedor1999@ya.ru --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme-challenge:/tmp/acme-challenge"
    environment:
      - TERM=xterm

networks:
  production_network: